FORMAT: X-1A
HOST: http://www.google.com/

# Analytics-test
The Analytics API allows you to obtain analytics data for your Video Cloud accounts directly. You can also view the built-in analytics reports in the Analytics Module of [Video Cloud Studio](http://videocloud.brightcove.com). Accessing the data programmatically gives you additional flexibility for such purposes as:

* Creating custom charts and displays
* Merging or aggregating data from multiple accounts
* Combining your video analytic data with other site analytics data

### <a id="metrics"></a>Available Metrics (by report type)
| Metric                | Player    | Video    | Referrer_domain    | Search_terms | Account Rollup   |
| -----                 | :----:    | :---:    | :-------------:    | :----------: | :------------:   |
| player_load           | **x**     |          |     **x**          | **x**        |  **x**           |
| video_impression      | **x**     |  **x**   |     **x**          | **x**        |  **x**           |
| video_view            | **x**     |  **x**   |     **x**          | **x**        |  **x**           |
| video_engagement      | **x**     |  **x**   |                    |              |  **x**           |
| video_percent_viewed  | **x**     |  **x**   |                    |              |  **x**           |
| video_seconds_viewed  | **x**     |  **x**   |                    |              |  **x**           |
| active_media          |           |          |                    |              |  **x**           |
| bytes_in              |           |          |                    |              |  **x**           |
| bytes_out             |           |          |                    |              |  **x**           |
| bytes_overhead        |           |          |                    |              |  **x**           |
| bytes_stored          |           |          |                    |              |  **x**           |
| bytes_player          |           |          |                    |              |  **x**           |

Welcome to the our sample API documentation. All comments can be written in (support [Markdown](http://daringfireball.net/projects/markdown/syntax) syntax)
---

--
Shopping Cart Resources
The following is a section of resources related to the shopping cart
--

List products added into your shopping-cart. (comment block again in Markdown)
GET /shopping-cart
< 200
< Content-Type: application/json
{ "items": [
{ "url": "/shopping-cart/1", "product":"2ZY48XPZ", "quantity": 1, "name": "New socks", "price": 1.25 }
] }

Save new products in your shopping cart
POST /shopping-cart
> Content-Type: application/json
{ "product":"1AB23ORM", "quantity": 2 }
< 201
< Content-Type: application/json
{ "status": "created", "url": "/shopping-cart/2" }

-- Payment Resources --

This resource allows you to submit payment information to process your *shopping cart* items
POST /payment
{ "cc": "12345678900", "cvc": "123", "expiry": "0112" }
< 200
{ "receipt": "/payment/receipt/1" }