HOST: https://data.brightcove.com/analytics-api/videocloud

--- Analytics API v1 ---
---
The Analytics API allows you to obtain analytics data for your Video Cloud accounts directly. You can also view the built-in analytics report in the Analytics Module of Video Cloud Studio. Accessing the data programmatically gives you additional flexibility for such purposes as:

*Creating custom charts and displays
*Merging or aggregating data from multiple accounts
*Combining your video analytic data with other site analytics data

---

--
Report
You can request reports using the path <code>/account/{accountId}/report</code>

###Parameters

| Parameter  | Required | Default     | Description |
| :-------:  | :------: | :-----:     | :---------: |
| dimensions | yes      | none        | The dimesion(s) to report on &mdash; one or more of the following values in a comma-delimited list: *video*, *player*, *referrer_domain*, *search_terms*, *source_type*, *device_type*, *device_os* |


* dimensions (required): the dimension(s) to report on
--
List products added into your shopping-cart. (comment block again in Markdown)
GET /account/{accountId}/report?dimensions={dimensions}&where={where}&limit={limit}&offset={offset}&from={from}&to={to}&sort={sort}
< 200
< Content-Type: application/json
{
    "account": "20318290001",
    "item_count": 123,
    "items": [
        {
            "video": "2127145422001",
            "video_duration": "124",
            "video_engagement_1": 0,
            "video_engagement_25": 4,
            "video_engagement_50": 2,
            "video_engagement_75": 2,
            "video_engagement_100": 2,
            "video_impression": 65,
            "video_name": "Creating a Playlist (Japanese)",
            "video_percent_viewed": 297.81667977970096,
            "video_seconds_viewed": 369,
            "video_view": 9
        }
    ]
}

Save new products in your shopping cart
POST /shopping-cart
> Content-Type: application/json
{ "product":"1AB23ORM", "quantity": 2 }
< 201
< Content-Type: application/json
{ "status": "created", "url": "/shopping-cart/2" }


-- Payment Resources --
This resource allows you to submit payment information to process your *shopping cart* items
POST /payment
{ "cc": "12345678900", "cvc": "123", "expiry": "0112" }
< 200
{ "receipt": "/payment/receipt/1" }